version: "3"

services:
  metadata:
    build: ./metadata/.
    container_name: metadata
    volumes:
      - ./metadata/src:/app
    ports:
      - 8080:8080

  rating:
    build: ./rating/.
    container_name: rating
    volumes:
      - ./rating/src:/app
    ports:
      - 8081:8080
    environment:
      - METADATA_API_URL=http://metadata:8080/metadata

  movie:
    build: ./movie/.
    container_name: movie
    volumes:
      - ./movie/src:/app
    ports:
      - 8082:8080
    environment:
      - METADATA_API_URL=http://metadata:8080/metadata
      - RATING_API_URL=http://rating:8080/rating
